// Generated by scripts/generate_aoti_wrappers.py. Do not edit by hand.
// clang-format off

#include "aoti_torch_mpi_ext.h"

#include "torch_bindings.h"

#include <ATen/record_function.h>

#include <torch/csrc/inductor/aoti_torch/utils.h>

using namespace torch::aot_inductor;
using namespace torch_mpi_ext;

AOTITorchError aoti_torch_mcpu_myadd_out(
    AtenTensorHandle a,
    AtenTensorHandle b,
    AtenTensorHandle out,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_myadd_out", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    myadd_out_cpu(
        *tensor_handle_to_tensor_pointer(a),
        *tensor_handle_to_tensor_pointer(b),
        *tensor_handle_to_tensor_pointer(out));
  });
}

AOTITorchError aoti_torch_mcpu_all_reduce_(
    AtenTensorHandle input,
    int64_t comm_ptr,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_all_reduce_", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    all_reduce_(
        *tensor_handle_to_tensor_pointer(input),
        comm_ptr);
  });
}

AOTITorchError aoti_torch_mcpu_all_gather_into_tensor_out(
    AtenTensorHandle output,
    AtenTensorHandle input,
    int64_t comm_ptr,
    int64_t dim,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_all_gather_into_tensor_out", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    all_gather_into_tensor_out(
        *tensor_handle_to_tensor_pointer(output),
        *tensor_handle_to_tensor_pointer(input),
        comm_ptr,
        dim);
  });
}

AOTITorchError aoti_torch_mcpu_reduce_scatter_out(
    AtenTensorHandle output,
    AtenTensorHandle input,
    int64_t comm_ptr,
    int64_t dim,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_reduce_scatter_out", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    reduce_scatter_out(
        *tensor_handle_to_tensor_pointer(output),
        *tensor_handle_to_tensor_pointer(input),
        comm_ptr,
        dim);
  });
}

AOTITorchError aoti_torch_mcpu_reduce_scatterv_out(
    AtenTensorHandle output,
    AtenTensorHandle input,
    AtenTensorHandle sizes,
    int64_t comm_ptr,
    int64_t dim,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_reduce_scatterv_out", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    reduce_scatterv_out(
        *tensor_handle_to_tensor_pointer(output),
        *tensor_handle_to_tensor_pointer(input),
        *tensor_handle_to_tensor_pointer(sizes),
        comm_ptr,
        dim);
  });
}

AOTITorchError aoti_torch_mcpu_alltoallv_out(
    AtenTensorHandle recvbuf,
    AtenTensorHandle sendbuf,
    AtenTensorHandle sendcounts,
    AtenTensorHandle sdispls,
    AtenTensorHandle recvcounts,
    AtenTensorHandle rdispls,
    int64_t comm_ptr,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_alltoallv_out", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    alltoallv_out(
        *tensor_handle_to_tensor_pointer(recvbuf),
        *tensor_handle_to_tensor_pointer(sendbuf),
        *tensor_handle_to_tensor_pointer(sendcounts),
        *tensor_handle_to_tensor_pointer(sdispls),
        *tensor_handle_to_tensor_pointer(recvcounts),
        *tensor_handle_to_tensor_pointer(rdispls),
        comm_ptr);
  });
}

AOTITorchError aoti_torch_mcpu_alltoall_out(
    AtenTensorHandle recvbuf,
    AtenTensorHandle sendbuf,
    int64_t comm_ptr,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_alltoall_out", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    alltoall_out(
        *tensor_handle_to_tensor_pointer(recvbuf),
        *tensor_handle_to_tensor_pointer(sendbuf),
        comm_ptr);
  });
}

AOTITorchError aoti_torch_mcpu_all_reduce__wrapper(
    AtenTensorHandle input,
    AtenTensorHandle comm_ptr_wrapper,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_all_reduce__wrapper", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    all_reduce__wrapper(
        *tensor_handle_to_tensor_pointer(input),
        *tensor_handle_to_tensor_pointer(comm_ptr_wrapper));
  });
}

AOTITorchError aoti_torch_mcpu_all_gather_into_tensor_out_wrapper(
    AtenTensorHandle output,
    AtenTensorHandle input,
    AtenTensorHandle comm_ptr_wrapper,
    int64_t dim,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_all_gather_into_tensor_out_wrapper", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    all_gather_into_tensor_out_wrapper(
        *tensor_handle_to_tensor_pointer(output),
        *tensor_handle_to_tensor_pointer(input),
        *tensor_handle_to_tensor_pointer(comm_ptr_wrapper),
        dim);
  });
}

AOTITorchError aoti_torch_mcpu_reduce_scatter_out_wrapper(
    AtenTensorHandle output,
    AtenTensorHandle input,
    AtenTensorHandle comm_ptr_wrapper,
    int64_t dim,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_reduce_scatter_out_wrapper", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    reduce_scatter_out_wrapper(
        *tensor_handle_to_tensor_pointer(output),
        *tensor_handle_to_tensor_pointer(input),
        *tensor_handle_to_tensor_pointer(comm_ptr_wrapper),
        dim);
  });
}

AOTITorchError aoti_torch_mcpu_reduce_scatterv_out_wrapper(
    AtenTensorHandle output,
    AtenTensorHandle input,
    AtenTensorHandle sizes,
    AtenTensorHandle comm_ptr_wrapper,
    int64_t dim,
    [[maybe_unused]] void* output_args) {
  RECORD_FUNCTION("aoti_torch_mcpu_reduce_scatterv_out_wrapper", {});
  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({
    reduce_scatterv_out_wrapper(
        *tensor_handle_to_tensor_pointer(output),
        *tensor_handle_to_tensor_pointer(input),
        *tensor_handle_to_tensor_pointer(sizes),
        *tensor_handle_to_tensor_pointer(comm_ptr_wrapper),
        dim);
  });
}

// clang-format on
