#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

PACKAGE = "torch_mpi_ext"
DEVICE = "mpi_ext"

GENERATED_HEADER = """// Generated by scripts/generate_aoti_wrappers.py. Do not edit by hand.
// clang-format off
"""

CLANG_FORMAT_ON = "// clang-format on\n"


@dataclass(frozen=True)
class Arg:
    schema_type: str
    name: str

    @property
    def is_tensor(self) -> bool:
        return self.schema_type.startswith("Tensor")

    @property
    def is_optional_tensor(self) -> bool:
        return self.is_tensor and "?" in self.schema_type


@dataclass(frozen=True)
class Op:
    name: str
    args: list[Arg]
    returns: str
    impl: str
    source: Path


def _join_schema_string(expr: str) -> str:
    return "".join(re.findall(r'"([^"\\]*(?:\\.[^"\\]*)*)"', expr))


def _extract_call_blocks(source: str, callee: str) -> list[str]:
    blocks: list[str] = []
    pos = 0
    needle = f"{callee}("
    while True:
        start = source.find(needle, pos)
        if start < 0:
            return blocks
        i = start + len(needle)
        depth = 1
        in_string = False
        escaped = False
        while i < len(source):
            ch = source[i]
            if in_string:
                if escaped:
                    escaped = False
                elif ch == "\\":
                    escaped = True
                elif ch == '"':
                    in_string = False
            else:
                if ch == '"':
                    in_string = True
                elif ch == "(":
                    depth += 1
                elif ch == ")":
                    depth -= 1
                    if depth == 0:
                        blocks.append(source[start + len(needle):i])
                        pos = i + 1
                        break
            i += 1
        else:
            raise ValueError(f"unterminated {callee} call")


def _split_schema_args(args_text: str) -> list[str]:
    args: list[str] = []
    start = 0
    depth = 0
    for idx, ch in enumerate(args_text):
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        elif ch == "," and depth == 0:
            args.append(args_text[start:idx])
            start = idx + 1
    args.append(args_text[start:])
    return args


def _parse_arg(text: str) -> Arg:
    text = text.split("=", 1)[0].strip()
    schema_type, name = text.rsplit(" ", 1)
    return Arg(schema_type=schema_type.strip(), name=name.strip())


def _parse_schema(schema: str) -> tuple[str, list[Arg], str]:
    match = re.fullmatch(r"\s*([^(]+)\((.*)\)\s*->\s*(.+)\s*", schema)
    if not match:
        raise ValueError(f"unsupported schema format: {schema}")
    name, args_text, returns = match.groups()
    args = []
    if args_text.strip():
        args = [_parse_arg(part) for part in _split_schema_args(args_text)]
    return name.strip(), args, returns.strip()


def _parse_defs(source: str) -> dict[str, tuple[list[Arg], str]]:
    result = {}
    for block in _extract_call_blocks(source, "m.def"):
        schema = _join_schema_string(block)
        if not schema or "->" not in schema:
            continue
        name, args, returns = _parse_schema(schema)
        result[name] = (args, returns)
    return result


def _parse_impls(source: str) -> dict[str, str]:
    result = {}
    for block in _extract_call_blocks(source, "m.impl"):
        name_match = re.search(r'"([^"]+)"', block)
        if not name_match:
            continue
        impl_match = re.search(r"TORCH_FN\((.*)\)", block, re.S)
        if impl_match:
            impl = impl_match.group(1)
        else:
            parts = block.split(",", 1)
            if len(parts) != 2:
                continue
            impl = parts[1]
        impl = impl.strip().rstrip(";").strip()
        if impl.startswith("&"):
            impl = impl[1:].strip()
        result[name_match.group(1)] = " ".join(impl.split())
    return result


def _c_type(arg: Arg) -> str | None:
    typ = arg.schema_type
    if arg.is_optional_tensor:
        return "AtenTensorHandle*"
    if arg.is_tensor:
        return "AtenTensorHandle"
    if typ == "int":
        return "int64_t"
    if typ == "float":
        return "double"
    if typ == "bool":
        return "int32_t"
    if typ == "Scalar":
        return "double"
    return None


def _call_expr(arg: Arg) -> str:
    if arg.is_optional_tensor:
        return f"resolve_tensor_dispatch_flags({arg.name})"
    if arg.is_tensor:
        return f"*tensor_handle_to_tensor_pointer({arg.name})"
    return arg.name


def _supported(args: list[Arg], returns: str) -> tuple[bool, str]:
    if returns != "()":
        return False, f"return type {returns}"
    for arg in args:
        if _c_type(arg) is None:
            return False, f"argument {arg.name} has type {arg.schema_type}"
    return True, ""


def _collect_ops(sources: list[tuple[Path, str]]) -> tuple[list[Op], list[str]]:
    defs: dict[str, tuple[list[Arg], str, Path]] = {}
    impls: dict[str, tuple[str, Path]] = {}
    for path, source in sources:
        for name, (args, returns) in _parse_defs(source).items():
            defs.setdefault(name, (args, returns, path))
        for name, impl in _parse_impls(source).items():
            impls[name] = (impl, path)

    ops = []
    skipped = []
    for name, (args, returns, source_path) in defs.items():
        impl_info = impls.get(name)
        if impl_info is None:
            skipped.append(f"{name} ({source_path.name}): no m.impl registration")
            continue
        impl, _impl_path = impl_info
        ok, reason = _supported(args, returns)
        if not ok:
            skipped.append(f"{name} ({source_path.name}): {reason}")
            continue
        ops.append(Op(name=name, args=args, returns=returns, impl=impl, source=source_path))
    return ops, skipped


def _prototype(op: Op, *, trailing_semicolon: bool) -> str:
    prefix = "AOTI_TORCH_EXPORT AOTITorchError" if trailing_semicolon else "AOTITorchError"
    lines = [f"{prefix} aoti_torch_{DEVICE}_{op.name}("]
    params = [f"    {_c_type(arg)} {arg.name}" for arg in op.args]
    params.append("    [[maybe_unused]] void* output_args")
    for idx, param in enumerate(params):
        suffix = "," if idx + 1 < len(params) else (");" if trailing_semicolon else ")")
        lines.append(param + suffix)
    return "\n".join(lines)


def _generate_header(ops: list[Op], skipped: list[str]) -> str:
    chunks = [
        GENERATED_HEADER,
        "#pragma once\n",
        "#include <torch/csrc/inductor/aoti_torch/c/shim.h>\n",
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n",
    ]
    for op in ops:
        chunks.append(_prototype(op, trailing_semicolon=True))
        chunks.append("")
    if skipped:
        chunks.append("// Skipped wrappers:")
        chunks.extend(f"// - {item}" for item in skipped)
        chunks.append("")
    chunks.append("#ifdef __cplusplus\n} // extern \"C\"\n#endif\n")
    chunks.append(CLANG_FORMAT_ON)
    return "\n".join(chunks)


def _generate_cpp(ops: list[Op]) -> str:
    chunks = [
        GENERATED_HEADER,
        '#include "aoti_torch_mpi_ext.h"\n',
        '#include "torch_bindings.h"\n',
        "#include <torch/csrc/inductor/aoti_torch/utils.h>\n",
        "using namespace torch::aot_inductor;",
        f"using namespace {PACKAGE};\n",
    ]
    for op in ops:
        chunks.append(_prototype(op, trailing_semicolon=False) + " {")
        chunks.append("  AOTI_TORCH_CONVERT_EXCEPTION_TO_ERROR_CODE({")
        call_args = ",\n        ".join(_call_expr(arg) for arg in op.args)
        if call_args:
            chunks.append(f"    {op.impl}(\n        {call_args});")
        else:
            chunks.append(f"    {op.impl}();")
        chunks.append("  });")
        chunks.append("}")
        chunks.append("")
    chunks.append(CLANG_FORMAT_ON)
    return "\n".join(chunks)


def _generate_op_list(ops: list[Op], skipped: list[str]) -> str:
    lines = [
        "Generated by scripts/generate_aoti_wrappers.py. Do not edit by hand.",
        "",
        f"Generated wrappers: {len(ops)}",
        "",
    ]
    for op in ops:
        lines.append(f"{op.name}\taoti_torch_{DEVICE}_{op.name}\t{op.source}")
    if skipped:
        lines.extend(["", f"Skipped operators: {len(skipped)}", ""])
        lines.extend(skipped)
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    csrc_dir = root / PACKAGE / "csrc"
    sources = [
        (path.relative_to(root), path.read_text())
        for path in sorted(csrc_dir.glob("*.cpp"))
        if path.name != "aoti_torch_mpi_ext.cpp"
    ]
    ops, skipped = _collect_ops(sources)
    outputs = {
        root / PACKAGE / "include/aoti_torch_mpi_ext.h": _generate_header(ops, skipped),
        root / PACKAGE / "csrc/aoti_torch_mpi_ext.cpp": _generate_cpp(ops),
        root / PACKAGE / "include/aoti_torch_mpi_ext_ops.txt": _generate_op_list(ops, skipped),
    }

    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if stale:
            raise SystemExit("stale generated AOTI wrappers: " + ", ".join(str(path) for path in stale))
        return

    for path, content in outputs.items():
        path.write_text(content)
    print(f"generated {len(ops)} AOTI wrappers")
    if skipped:
        print(f"skipped {len(skipped)} operators")


if __name__ == "__main__":
    main()
